FROM golang:latest

WORKDIR /app

COPY go.mod .

COPY go.sum .

RUN go mod download

COPY . .

RUN go build

RUN go test > tests-results.txt

RUN echo "Executing tests, results can be found at tests-results.txt"
