FROM golang:latest

WORKDIR /app

COPY go.mod .

COPY go.sum .

RUN go mod download

COPY . .

RUN go build

RUN echo "Executing tests, results can be found at tests-results.txt"

CMD ["/bin/sh", "-c", "go test > output.txt"]
